env:
  requirements: '["appdirs==1.4.4","attrs==20.3.0","autopep8==1.5.6","backcall==0.2.0","black==20.8b1","Brotli==1.0.9","click==7.1.2","colorama==0.4.4","dash==1.17.0","dash-bootstrap-components==0.10.7","dash-core-components==1.13.0","dash-html-components==1.1.1","dash-renderer==1.8.3","dash-table==4.11.0","decorator==5.0.6","dnspython==1.16.0","Flask==1.1.2","Flask-Compress==1.8.0","future==0.18.2","gunicorn==20.0.4","ipykernel==5.5.3","ipython==7.22.0","ipython-genutils==0.2.0","itsdangerous==1.1.0","jedi==0.18.0","Jinja2==2.11.2","jsonschema==3.2.0","jupyter-client==6.1.12","jupyter-core==4.7.1","MarkupSafe==1.1.1","mypy-extensions==0.4.3","nbformat==5.1.3","numpy==1.19.4","pandas==1.1.4","parso==0.8.2","pathspec==0.8.1","pickleshare==0.7.5","plotly==4.12.0","prompt-toolkit==3.0.18","pycodestyle==2.7.0","Pygments==2.8.1","pymongo==3.11.2","pyrsistent==0.17.3","python-dateutil==2.8.1","pytz==2020.4","pywin32==300","pyzmq==22.0.3","regex==2021.4.4","retrying==1.3.3","schedule==1.1.0","six==1.15.0","toml==0.10.2","tornado==6.1","traitlets==5.0.5","typed-ast==1.4.3","typing-extensions==3.7.4.3","Unidecode==1.2.0","wcwidth==0.2.5","Werkzeug==1.0.1",]'
  
on:
  schedule:
    # runs at 06:00 UTC every day
    - cron: "50 17 * * *"
    
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Executa o preprocessing
      run: |
        python preprocessing.py
